
player1-human---------------
Thread-3 needed 0.0050 sec
B5 from -5,-11 to 4,4

computer-player2---------------
Thread-4 needed 0.152 sec
a1 from -6,-11 to 0,0

player1-human---------------
Thread-5 needed 0.0010 sec
C3 from -5,-11 to 4,3

computer-player2---------------
Thread-6 needed 0.0010 sec
c4 from -6,-11 to 0,1

player1-human---------------
Thread-7 needed 0.0010 sec
B4 from -5,-11 to 4,3
B4 from 4,3 to 3,3

computer-player2---------------
Thread-8 needed 0.0010 sec
b1 from -6,-11 to 0,1
b1 from 0,1 to 1,1

player1-human---------------
Thread-9 needed 0.066 sec
B3 from -5,-11 to 4,4
B3 from 4,4 to 3,4
B4 from 3,3 to 2,3
B3 from 3,4 to 3,3
C3 from 4,3 to 4,2
B3 from 3,3 to 3,2
B3 from 3,2 to 3,1

computer-player2---------------
Thread-10 needed 0.0020 sec
a5 from -6,-11 to 1,0
a1 from 0,0 to 0,1
a1 from 0,1 to 0,2

player1-human---------------
Thread-11 needed 0.03 sec
C4 from -5,-11 to 4,3
C3 from 4,2 to 3,2
B3 from 3,1 to 2,1
B3 from 2,1 to 1,1
C4 from 4,3 to 4,2
C3 from 3,2 to 3,1
B3 from 1,1 to 1,0

computer-player2---------------
Thread-12 needed 1.01 sec
a4 from -6,-11 to 0,0
a1 from 0,2 to 1,2
a5 from 1,0 to 2,0
a4 from 0,0 to 1,0
b1 from 1,1 to 2,1
a4 from 1,0 to 1,1
a1 from 1,2 to 2,2
a4 from 1,1 to 1,2
b1 from 2,1 to 3,1
a1 from 2,2 to 3,2
a1 from 3,2 to 4,2
a1 from 4,2 to 4,3

player1-human---------------
Thread-13 needed 0.0010 sec
A3 from -5,-11 to 4,3

computer-player2---------------
Thread-14 needed 0.031 sec
c5 from -6,-11 to 0,0
c4 from 0,1 to 1,1
c5 from 0,0 to 0,1
a4 from 1,2 to 2,2
c4 from 1,1 to 1,2
a5 from 2,0 to 3,0
a4 from 2,2 to 2,3

player1-human---------------
Thread-15 needed 0.0020 sec
A5 from -5,-11 to 4,4
A5 from 4,4 to 3,4
A5 from 3,4 to 3,3
A5 from 3,3 to 3,2

computer-player2---------------
Thread-16 needed 0.856 sec
b5 from -6,-11 to 0,0
c5 from 0,1 to 1,1
b5 from 0,0 to 0,1
c4 from 1,2 to 2,2
c5 from 1,1 to 1,2
b5 from 0,1 to 0,2
a4 from 2,3 to 3,3
c4 from 2,2 to 2,3
c5 from 1,2 to 1,3
c5 from 1,3 to 1,4
a5 from 3,0 to 4,0
a4 from 3,3 to 3,4

player1-human---------------
Thread-17 needed 0.0020 sec
C2 from -5,-11 to 4,3
C2 from 4,3 to 3,3

computer-player2---------------
Thread-18 needed 0.038 sec
b4 from -6,-11 to 0,1
b5 from 0,2 to 1,2
b4 from 0,1 to 0,2
b4 from 0,2 to 0,3
b4 from 0,3 to 0,4
c5 from 1,4 to 2,4
c5 from 2,4 to 3,4

player1-human---------------
Thread-19 needed 0.0020 sec
B1 from -5,-11 to 4,3
B5 from 4,4 to 3,4
B5 from 3,4 to 2,4

computer-player2---------------
Thread-20 needed 0.042 sec
b3 from -6,-11 to 0,1
b3 from 0,1 to 0,2
b3 from 0,2 to 0,3
b4 from 0,4 to 1,4
b4 from 1,4 to 2,4
b4 from 2,4 to 3,4

player1-human---------------
Thread-21 needed 0.106 sec
C1 from -5,-11 to 4,3
C4 from 4,2 to 3,2
C4 from 3,2 to 2,2
C1 from 4,3 to 4,2
C1 from 4,2 to 3,2
C1 from 3,2 to 3,1
C2 from 3,3 to 2,3
C4 from 2,2 to 1,2

computer-player2---------------
Thread-22 needed 0.0 sec
c1 from -6,-11 to 0,0

player1-human---------------
Thread-23 needed 19.37 sec
A1 from -5,-11 to 4,4
B1 from 4,3 to 3,3
C1 from 3,1 to 2,1
C2 from 2,3 to 1,3
C2 from 1,3 to 0,3
A1 from 4,4 to 3,4
B1 from 3,3 to 2,3
C1 from 2,1 to 1,1
B5 from 2,4 to 1,4
A1 from 3,4 to 2,4
A1 from 2,4 to 1,4
A1 from 1,4 to 0,4
C1 from 1,1 to 0,1

computer-player2---------------
Thread-24 needed 0.0020 sec
c3 from -6,-11 to 1,0
c1 from 0,0 to 0,1
c1 from 0,1 to 0,2

player1-human---------------
Thread-25 needed 0.018 sec
B2 from -5,-11 to 3,4
B2 from 3,4 to 3,3
C2 from 0,3 to 0,2
B2 from 3,3 to 3,2
B2 from 3,2 to 3,1
C2 from 0,2 to 0,1

computer-player2---------------
Thread-26 needed 0.0010 sec
b2 from -6,-11 to 0,0
b3 from 0,3 to 1,3
b3 from 1,3 to 2,3

player1-human---------------
Thread-27 needed 0.092 sec
A4 from -5,-11 to 4,4
A3 from 4,3 to 3,3
A3 from 3,3 to 2,3
A4 from 4,4 to 4,3
A4 from 4,3 to 4,2
C4 from 1,2 to 1,1
A4 from 4,2 to 4,1
C4 from 1,1 to 1,0

computer-player2---------------
Thread-28 needed 0.0040 sec
a2 from -6,-11 to 1,0
a5 from 4,0 to 4,1
a2 from 1,0 to 1,1
a5 from 4,1 to 4,2
a5 from 4,2 to 4,3

player1-human---------------
Thread-29 needed 0.0080 sec
C5 from -5,-11 to 3,4
B5 from 1,4 to 1,3
A5 from 3,2 to 2,2
A5 from 2,2 to 1,2
B5 from 1,3 to 0,3

computer-player2---------------
Thread-30 needed 0.0030 sec
a3 from -6,-11 to 1,0
a3 from 1,0 to 2,0
a3 from 2,0 to 2,1
a2 from 1,1 to 1,2

player1-human---------------
Thread-31 needed 0.044 sec
A2 from -5,-11 to 4,4
A2 from 4,4 to 3,4
A2 from 3,4 to 2,4
A3 from 2,3 to 1,3
A2 from 2,4 to 2,3
A3 from 1,3 to 1,2

computer-player2---------------
Thread-32 needed 0.183 sec
c2 from -6,-11 to 0,0
c3 from 1,0 to 1,1
c2 from 0,0 to 1,0
a3 from 2,1 to 2,2
c3 from 1,1 to 2,1
c2 from 1,0 to 1,1
c3 from 2,1 to 3,1
c3 from 3,1 to 3,2
c1 from 0,2 to 0,3
c3 from 3,2 to 3,3
c3 from 3,3 to 3,4
